!This program requires a file having the spin densities for the system of
!interest in different electronic configurations and the energy associated with
!the system in that electronic configuration. Besides this, the program requires 
!another file having details about the number of magnetic centres and the Hamiltonian. 
!Using these two files, this program lets one calculate all possible J values for the
!system. If you have data for n configurations and you need j coupling constants
!then this program calculates all nCj coupling constants (provided n>j). In each
!calculation you need to sacrifice one equation. Thus you basically end up with
!n sets of (n-1)Cj coupling constants, all of which are calculated. The average
!per set and the total average of the coupling constant is also calculated.

!All subroutines called here are in the modul_lib.f90 file unless specified
!otherwise

Program jval_calc
 Use Iso_Fortran_Env
 Use init
 Use modul_lib 
 Use enrg_frm_jval
 Call Get_Command_Argument(1, FileName1)
 Call Get_Command_Argument(2, FileName2)
 If (trim(Filename1) == '' .Or. trim(Filename2) == '') Then
        Write(12,*) 'The input file name or the spin density filename has not been provided.'
        Write(12,*) 'Aborting'
        STOP          
 End if

 inp_file = trim(Filename1) !// '.inp'
#ifdef formal
 Outfile = trim(Filename1) // '_form.out'
#else
 Outfile = trim(Filename1) // '_spin.out'
#endif
 stdv = .FALSE.
 Open (Unit = 11, file = inp_file, action = 'read', position = 'rewind', iostat = ios)
 Open (Unit = 12, file = Outfile, status = 'unknown', action = 'readwrite')
 Open (Unit = 13, file = FileName2, action = 'read', position = 'rewind', iostat = ios)

#ifdef formal
 Open (Unit = 14, file = 'singul', status = 'unknown', action = 'readwrite')
 Open (Unit = 15, file = 'bigg', status = 'unknown', action = 'readwrite')
 Open (Unit = 16, file = 'nrg_frm_jval_formal', status = 'unknown', action = 'readwrite')
#else              
 Open (Unit = 14, file = 'singul', action = 'read', position = 'rewind', iostat = ios)
 Open (Unit = 16, file = 'nrg_frm_jval', status = 'unknown', action = 'readwrite')
 Inquire (file = 'singul', exist=exis)
 If (exis .eqv. .FALSE.) then
        Write(12,*)  "The file 'singul' is missing. Run the formal spin code first."
        STOP           
 End If
#endif 

 Call cpu_time(start)
! Write(*,*) 'Report wiil be available in the file', Outfile
! Write(*,*) 'Energy related to energy of all possible spin configs'
!
#ifdef formal
! Write(*,*) 'is available in the file nrg_frm_jval_formal'
#else                
! Write(*,*) 'is available in the file nrg_frm_jval'
#endif
 
#ifdef formal

 Write(12,*) '               ********************************'
 Write(12,*) '               *          EJ_calc_form        *'
 Write(12,*) '               ********************************'
 Write(12,*) ' part of the J2suscep packager for calculating coupling constants'
 Write(12,*) ' and magnestic susceptability '
 Write(12,*) ''
 Write(12,*) ' EJ_calc_form calculates the coupling constant and singular' 
 Write(12,*) ' matrices using formal (integer) spins. This singular matrices'
 Write(12,*) ' can then be used to assist the calculation of the coupling'
 Write(12,*) ' constrants using calcilated (non-integer) spins using EJ_calc'
 Write(12,*) ''
 Write(12,*) ''
 Write(12,*) '-------Calculating J values from Formal Spins-------'
 Write(12,*) 'This program will convert spin denstities to formal spins no'
 Write(12,*) 'matter what you give and will use the formal spins to solve everything.'
 Write(12,*) 'If you want to use spin densities, use a different code. Two extra'
 Write(12,*) "files 'bigg' and 'singul' will also be written. 'singul' is required"
 Write(12,*) "for any code the code that uses the spin densities. The file 'bigg'"
 Write(12,*) " tells you which set of equation has large values (>50 cm-1)"
 Write(12,*)
#else
 Write(12,*) '               ********************************'
 Write(12,*) '               *          EJ_calc_spin        *'
 Write(12,*) '               ********************************'
 Write(12,*) ' part of the J2suscep packager for calculating coupling constants'
 Write(12,*) ' and magnestic susceptability '
 Write(12,*) ''
 Write(12,*) ' EJ_calc_spin calculates the coupling constants uing calculated (non-integer)'
 Write(12,*) ' spins and using the non-singluar solutions of EJ_calc_form   '
 Write(12,*) ''
 Write(12,*) '-------Calculating J values from Spin Densities-------'
 Write(12,*) 'This program will use the spin denstities and will not convert the'
 Write(12,*) 'spin terms to formal spins.'
 Write(12,*) 'If you want to use any kind of spin densities, use this code. An extra'
 Write(12,*) "file 'singul' is required for this to run. This can be generated by"
 Write(12,*) "the code for formal spins. Then run this code"
 Write(12,*)
#endif

 
 Call init1() !from init.f90
 Call jvals() !Setting up the J value matrix (jval)  and determining the coefficients of
              !each J value
 Call solv() !Obtaining all possible J values.
 Call avrg_calcs()
 !The following loop section puts a constraint on the J value sets that will be
 !considered by choosing only those sets that are within 3 standard deviations.
 !The loop essentially checks the standard deviation and removes the values
 !beyond 3 standard deviations, and recalculates the standard deviation and repeat
 !this cycle until self consistency is achieved.
 stdv = .FALSE.
 139 Format(i2)
 Write(12,*) 'Removing solutions in which J-values deviate by more than 3 standard deviations'
 Write(12,*)'Standard deviation (percentage standard deviation) on different J-values:'
 Write (12,'(a)', advance = 'no')  'non-singular equations'
 Do i = 1, Size(jpos) - 1
         Write (12,'(a)', advance = 'no') '      '
         Write (12,'(a)', advance = 'no') 'J'
         Write (12, 139, advance = 'no') i
         Write (12,'(a)', advance = 'no') '    '
 End Do
 
 Do While(stdv .eqv. .FALSE.)
        Call std_dev(tot_avg)
 End Do
 Write(12,*)
 Write(12,*) 'Self-consistency achieved!'
 Call final_print()
 Call backtrack1(jval, tot_avg)
 Call avg_spin()       !from enrg_frm_jval.f90
 Call all_poss_spins() !from enrg_frm_jval.f90
 Call cpu_time(finish)
 Write(12,*) 'Time taken(sec) in program execution', finish-start
 Write(12,*) '---End Of File---'
 Deallocate (jpos, hamil, hamil1, hamil2, spin)

#ifdef formal 
 Deallocate (jval_trkr)
#endif

 Close(11)
 Close(12)
 Close(13)
 Close(14)
 Close(16)
#ifdef formal
 Close(15)
#endif

End Program jval_calc
